# -*- coding: utf-8 -*-
"""download_data.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d9mAIBf36wyj8Ib68coEu7THTDgRmqpq
"""

import kagglehub
import pandas as pd
import os

def load_kaggle_dataset(dataset_id, target_folder="data")
    try:
        # Скачиваем датасет
        dataset_path = kagglehub.dataset_download(dataset_id)
        print(f"Датасет скачан в: {dataset_path}")

        # Ищем CSV‑файлы
        csv_files = [
            f for f in os.listdir(dataset_path)
            if f.lower().endswith('.csv')
        ]

        if not csv_files:
            print("В датасете нет CSV‑файлов.")
            return None

        # Загружаем первый найденный CSV
        csv_file_path = os.path.join(dataset_path, csv_files[0])
        df = pd.read_csv(csv_file_path)
        print(f"Успешно загружен файл: {csv_files[0]}")
        print(f"Размер датасета: {df.shape}")
        return df

    except Exception as e:
        print(f"Ошибка при загрузке датасета: {e}")
        return None

# Использование
df = load_kaggle_dataset("evan65549/health-and-fitness-dataset")
if df is not None:
    print(df.head())